{% set name = "jupyter_enterprise_gateway" %}
{% set version = "3.2.0" %}
{% set sha256 = "e98f5857027d9bd7e835c1056fc26ed132f7bdb07f696eb420338f47ed6efd7f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-enterprisegateway = enterprise_gateway:launch_instance

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.5

  run:
    - python >=3.7
    - docker-py >=3.5.0
    - future
    - jinja2 >=3.1
    - jupyter_client >=6.1.12,<7.0  # Remove cap once EG supports kernel provisioners
    - jupyter_core >=4.7.0
    - jupyter_server >=1.3,<2.0  # Remove cap (increase floor) once EG supports kernel provisioners
    - paramiko >=2.11
    - pexpect >=4.8.0
    - pycryptodomex >=3.9.7
    - python-kubernetes >=18.20.0
    - pyzmq >=17.0,<25.0  # Pyzmq 25 removes deprecated code that jupyter_client 6 uses, remove if v6 gets updated
    - requests >=2.14.2
    - tornado >=6.1
    - traitlets >=5.3.0
    - watchdog >=2.1.3
    - yarn-api-client >=1.0

test:
  imports:
    - enterprise_gateway
    - enterprise_gateway.services
    - enterprise_gateway.services.kernels
    - enterprise_gateway.services.processproxies
    - enterprise_gateway.services.sessions
  commands:
    - jupyter-enterprisegateway --help
    - jupyter enterprisegateway --help

about:
  home: https://github.com/jupyter/enterprise_gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A web server for spawning and communicating with remote Jupyter kernels

  description: |
    Jupyter Enterprise Gateway A lightweight, multi-tenant, scalable and secure gateway
    that enables Jupyter Notebooks to share resources across distributed clusters such
    as Apache Spark, Kubernetes and others.
  doc_url: http://jupyter-enterprise-gateway.readthedocs.io/en/latest/
  dev_url: https://github.com/jupyter/enterprise_gateway

extra:
  recipe-maintainers:
    - lresende
    - kevin-bates
