{% set name = "jupyter_enterprise_gateway" %}
{% set version = "3.0.0" %}
{% set sha256 = "53b73de87b1a91139d1e9cfd062f7eadf0aa3a2ccb9afd052699d7a537933d1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-enterprisegateway = enterprise_gateway:launch_instance

requirements:
  host:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - docker-py >=3.5.0
    - future >=0.18.2
# https://github.com/conda-forge/jupyter_enterprise_gateway-feedstock/pull/35#issuecomment-1099606384
# https://github.com/jupyter-server/enterprise_gateway/pull/1046
    - ipython_genutils >=0.2.0 # Include ipython_genutils in the requirements file for now and we'll remove it in the next release.
    - jinja2 >=3.1
    - jupyter_client >=6.1,<7.0
    - jupyter_core >=4.6.0
    - jupyter_server >=1.2
    - paramiko >=2.1.2
    - pexpect >=4.2.0
    - pycryptodomex >=3.9.7
    - python-kubernetes >=4.0.0
    - pyzmq >=17.0.0
    - requests >=2.7,<3.0
    - tornado >=6.1
    - traitlets >=4.3.3
    - watchdog >=2.1.3
    - yarn-api-client >=1.0

test:
  imports:
    - enterprise_gateway
    - enterprise_gateway.services
    - enterprise_gateway.services.kernels
    - enterprise_gateway.services.processproxies
    - enterprise_gateway.services.sessions
  commands:
    - jupyter-enterprisegateway --help
    - jupyter enterprisegateway --help

about:
  home: https://github.com/jupyter/enterprise_gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A web server for spawning and communicating with remote Jupyter kernels

  description: |
    Jupyter Enterprise Gateway A lightweight, multi-tenant, scalable and secure gateway
    that enables Jupyter Notebooks to share resources across distributed clusters such
    as Apache Spark, Kubernetes and others.
  doc_url: http://jupyter-enterprise-gateway.readthedocs.io/en/latest/
  dev_url: https://github.com/jupyter/enterprise_gateway

extra:
  recipe-maintainers:
    - lresende
    - kevin-bates
