{% set name = "jupyter_enterprise_gateway" %}
{% set version = "2.2.0" %}
{% set sha256 = "e2f50aa33b93ebfa7fc74217f59c929ed229be283e1b88c3c80d7f8585de92b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-enterprisegateway = enterprise_gateway:launch_instance

requirements:
  build:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - docker-py >=3.5.0
    - future >=0.18.2
    - jinja2 >=2.10
    - jupyter_client >=5.2.0
    - jupyter_core >=4.4.0
    - notebook >=5.7.6,<7.0
    - paramiko >=2.1.2
    - pexpect >=4.2.0
    - pycryptodomex >=3.9.7
    - python-kubernetes >=4.0.0
    - pyzmq >=17.0.0
    - requests >=2.7,<3.0
    - tornado >=4.2.0
    - traitlets >=4.3.3
    - yarn-api-client >=1.0

test:
  imports:
    - enterprise_gateway
    - enterprise_gateway.services
    - enterprise_gateway.services.kernels
    - enterprise_gateway.services.processproxies
    - enterprise_gateway.services.sessions
  commands:
    - jupyter-enterprisegateway --help
    - jupyter enterprisegateway --help

about:
  home: https://github.com/jupyter/enterprise_gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A web server for spawning and communicating with remote Jupyter kernels

  description: |
    Jupyter Enterprise Gateway A lightweight, multi-tenant, scalable and secure gateway
    that enables Jupyter Notebooks to share resources across distributed clusters such
    as Apache Spark, Kubernetes and others.
  doc_url: http://jupyter-enterprise-gateway.readthedocs.io/en/latest/
  dev_url: https://github.com/jupyter/enterprise_gateway

extra:
  recipe-maintainers:
    - lresende
    - kevin-bates
