{% set name = "jupyter_enterprise_gateway" %}
{% set version = "1.0.0" %}
{% set sha256 = "72cb9bfe1268f4d5a41ede57b91f1336d5f4cd44630f2d5be5ac261ce21d228b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script:
    - python -m pip install --no-deps --ignore-installed .
    - python -m pip install yarn-api-client>=0.2.3
  entry_points:
    - jupyter-enterprisegateway = enterprise_gateway:launch_instance

requirements:
  build:
    - python
    - pip

  run:
    - python
    - jupyter_core >=4.4.0
    - jupyter_client >=5.2.0
    - notebook >=5.3.0,<6.0
    - jupyter_kernel_gateway >=2.0.0
    - traitlets >=4.2.0
    - tornado >=4.2.0
    - requests >=2.7,<3.0
    - paramiko >=2.1.2
    - pexpect >=4.2.0
    - pycrypto >=2.6.1
    - pyzmq >=17.0.0

test:
  imports:
    - enterprise_gateway
    - enterprise_gateway.services
    - enterprise_gateway.services.kernels
    - enterprise_gateway.services.kernelspecs
    - enterprise_gateway.services.sessions
  commands:
    - jupyter-enterprisegateway --help
    - jupyter enterprisegateway --help

about:
  home: https://github.com/jupyter-incubator/enterprise_gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'A web server for spawning and communicating with remote Jupyter kernels'

  description: |
    Jupyter Enterprise Gateway is a lightweight, multi-tenant, scalable and secure gateway that enables
    Jupyter Notebooks to share resources across an Apache Spark cluster
  doc_url: http://jupyter-enterprise-gateway.readthedocs.io/en/latest/
  dev_url: https://github.com/jupyter-incubator/enterprise_gateway

extra:
  recipe-maintainers:
    - lresende
    - liukun1016
    - kevin-bates
