travis:
  secure:
    BINSTAR_TOKEN: T2Xz4wtT+pVndyKUEUljKvF1tcRmbqHkKSzIi9oLbVlxgdNEWd4tcYl0F7g0uzbJSWvy68ApweXIWVPbtr/kbVxNkKCXnvGkp6MM38nqYKA5AzGxqC4V+gF7JVBD3dmxTjbJgAoQaX1C06tBIWIHARPGz57vZcraScRCZuD8RseAARNIrgPaJ+ML6T8iEwPv7/8b9TDcbHSBsn8gtXbkVPkGfxJ9e+OfLxZYoT2DGwiTKbO3KGEPItxQ/e/Lejob/3WzBdUuTLtIRugIexRx7aKwZLZs99QnUnsGnaMaGVSKCR5Z36HHwmJRh+g8kcVxsL+h76WUpUEkdxmeEopTpog/w7wzH/9Sdxp+7vzue4NVPXBHKhjChaLvZcfZOnoH9Y2N/zbQhJZUfm7+JQ64pm/ffhhxdWQPGjO1blqZyYW4l4cjbKz9ENdADFMg+pWFEBLgZVCeTgMaS3z4SuTaeGnlnL2oCqcVyumL/F4jSh/StWsidGvxjxzoJ2ITXwxoy3obd5Y73JGyq9JLx8isYl4PVqLt/eMmDNlt5YzuVpnAeLbaFX6dHZOB7J4AJuZ4xR2UZMh9Mi16CZ0DJeD73sP00AsgwmJ6K0Ard6OOS0wHR8UzPufJpvmpahaQRiqEycpyrU1F0emIWNEipYoJL/MF4+x1Uh3/Rw+VXmo4UTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
